/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import aplicacionpi.ConnectionDB;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago
 */
public class AdicionarEmpleado extends javax.swing.JFrame {

    ConnectionDB conexion = new ConnectionDB("techcare");
    
    /**
     * Creates new form AdicionarEmpleado
     */
    public AdicionarEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(670,570);
        this.setTitle("ADICIONAR EMPLEADO");
    }

    public void goBack(){
        this.dispose();
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
    }
    
    public void AddEmployee(java.awt.event.ActionEvent evt){
        String idEmpleado = idTextField.getText();
        String primerNombre = primerNombreField.getText();
        String segundoNombre = segundoNombreField.getText();
        String primerApellido = primerApellidoField.getText();
        String segundoApellido = segundoApellidoField.getText();
        String telefono = telefonoField.getText();
        String direccion = direccionField.getText();
        String email = emailField.getText();
        String salario = salarioField.getText();
        
        try {
            Connection conn = conexion.conectar();

            PreparedStatement statement = conn.prepareStatement("INSERT INTO empleados (id_empleado, primer_nombre_empleado, segundo_nombre_empleado, primer_apellido_empleado, segundo_apellido_empleado, telefono_empleado, direccion_empleado, email_empleado, salario_empleado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
            statement.setString(1, idEmpleado);
            statement.setString(2, primerNombre);
            statement.setString(3, segundoNombre);
            statement.setString(4, primerApellido);
            statement.setString(5, segundoApellido);
            statement.setString(6, telefono);
            statement.setString(7, direccion);
            statement.setString(8, email);
            statement.setString(9, salario);
        
            statement.executeUpdate();

            conn.close();

            JOptionPane.showMessageDialog(null, "Empleado agregado correctamente.");
            wipeFields();
        
    } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al agregar empleado: " + e.getMessage());
    }
}
    
    public void wipeFields(){
                 idTextField.setText("");
                primerNombreField.setText("");
                segundoNombreField.setText("");
                primerApellidoField.setText("");
                segundoApellidoField.setText("");
                telefonoField.setText("");
                direccionField.setText("");
                emailField.setText("");               
                salarioField.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        Segundo_nombre = new javax.swing.JLabel();
        primerNombreField = new javax.swing.JTextField();
        Primer_apellido = new javax.swing.JLabel();
        segundoNombreField = new javax.swing.JTextField();
        Segundo_apellido = new javax.swing.JLabel();
        primerApellidoField = new javax.swing.JTextField();
        Teléfono = new javax.swing.JLabel();
        segundoApellidoField = new javax.swing.JTextField();
        Dirección = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        direccionField = new javax.swing.JTextField();
        Salario = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        wipe_btn = new javax.swing.JButton();
        salarioField = new javax.swing.JTextField();
        addition_btn = new javax.swing.JButton();
        Cédula = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        Primer_nombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADICIONAR EMPLEADO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idTextField.setBackground(new java.awt.Color(204, 204, 204));
        idTextField.setForeground(new java.awt.Color(51, 51, 51));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        Segundo_nombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Segundo_nombre.setForeground(new java.awt.Color(51, 51, 51));
        Segundo_nombre.setText("Segundo nombre:");

        primerNombreField.setBackground(new java.awt.Color(204, 204, 204));
        primerNombreField.setForeground(new java.awt.Color(51, 51, 51));
        primerNombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerNombreFieldActionPerformed(evt);
            }
        });

        Primer_apellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Primer_apellido.setForeground(new java.awt.Color(51, 51, 51));
        Primer_apellido.setText("Primer apellido:");

        segundoNombreField.setBackground(new java.awt.Color(204, 204, 204));
        segundoNombreField.setForeground(new java.awt.Color(51, 51, 51));

        Segundo_apellido.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Segundo_apellido.setForeground(new java.awt.Color(51, 51, 51));
        Segundo_apellido.setText("Segundo apellido:");

        primerApellidoField.setBackground(new java.awt.Color(204, 204, 204));
        primerApellidoField.setForeground(new java.awt.Color(51, 51, 51));

        Teléfono.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Teléfono.setForeground(new java.awt.Color(51, 51, 51));
        Teléfono.setText("Teléfono:");

        segundoApellidoField.setBackground(new java.awt.Color(204, 204, 204));
        segundoApellidoField.setForeground(new java.awt.Color(51, 51, 51));

        Dirección.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Dirección.setForeground(new java.awt.Color(51, 51, 51));
        Dirección.setText("Dirección:");

        telefonoField.setBackground(new java.awt.Color(204, 204, 204));
        telefonoField.setForeground(new java.awt.Color(51, 51, 51));

        Email.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 51, 51));
        Email.setText("Email:");

        direccionField.setBackground(new java.awt.Color(204, 204, 204));
        direccionField.setForeground(new java.awt.Color(51, 51, 51));

        Salario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Salario.setForeground(new java.awt.Color(51, 51, 51));
        Salario.setText("Salario:");

        emailField.setBackground(new java.awt.Color(204, 204, 204));
        emailField.setForeground(new java.awt.Color(51, 51, 51));

        wipe_btn.setBackground(new java.awt.Color(102, 153, 255));
        wipe_btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        wipe_btn.setForeground(new java.awt.Color(0, 0, 0));
        wipe_btn.setText("LIMPIAR");
        wipe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wipe_btnActionPerformed(evt);
            }
        });

        salarioField.setBackground(new java.awt.Color(204, 204, 204));
        salarioField.setForeground(new java.awt.Color(51, 51, 51));

        addition_btn.setBackground(new java.awt.Color(102, 153, 255));
        addition_btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addition_btn.setForeground(new java.awt.Color(0, 0, 0));
        addition_btn.setText("ADICIONAR");
        addition_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addition_btnActionPerformed(evt);
            }
        });

        Cédula.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Cédula.setForeground(new java.awt.Color(51, 51, 51));
        Cédula.setText("Cédula:");

        back_btn.setBackground(new java.awt.Color(102, 153, 255));
        back_btn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        back_btn.setForeground(new java.awt.Color(0, 0, 0));
        back_btn.setText("VOLVER");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        Primer_nombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Primer_nombre.setForeground(new java.awt.Color(51, 51, 51));
        Primer_nombre.setText("Primer nombre:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/proveedor-35.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(wipe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(addition_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Segundo_apellido)
                                .addGap(31, 31, 31)
                                .addComponent(segundoApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Segundo_nombre)
                                .addGap(31, 31, 31)
                                .addComponent(segundoNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Primer_nombre)
                            .addComponent(Primer_apellido)
                            .addComponent(Email)
                            .addComponent(Salario)
                            .addComponent(Dirección)
                            .addComponent(Teléfono)
                            .addComponent(Cédula)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primerNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primerApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cédula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundoNombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Segundo_nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primerApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Primer_apellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segundoApellidoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Segundo_apellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Teléfono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dirección))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salario))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addition_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wipe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primerNombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerNombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primerNombreFieldActionPerformed

    private void wipe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wipe_btnActionPerformed
        wipeFields();
    }//GEN-LAST:event_wipe_btnActionPerformed

    private void addition_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addition_btnActionPerformed
        AddEmployee(evt);
    }//GEN-LAST:event_addition_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        goBack();
    }//GEN-LAST:event_back_btnActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cédula;
    private javax.swing.JLabel Dirección;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Primer_apellido;
    private javax.swing.JLabel Primer_nombre;
    private javax.swing.JLabel Salario;
    private javax.swing.JLabel Segundo_apellido;
    private javax.swing.JLabel Segundo_nombre;
    private javax.swing.JLabel Teléfono;
    private javax.swing.JButton addition_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField direccionField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField primerApellidoField;
    private javax.swing.JTextField primerNombreField;
    private javax.swing.JTextField salarioField;
    private javax.swing.JTextField segundoApellidoField;
    private javax.swing.JTextField segundoNombreField;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JButton wipe_btn;
    // End of variables declaration//GEN-END:variables
}
